---
- name: OS-specific setup
  ansible.builtin.import_tasks: os_preflight.yml
  become: true

- name: Configure ingester
  ansible.builtin.include_tasks: configure.yml

- name: Enable and start ingester service
  ansible.builtin.include_tasks: service.yml
