// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/agenttransponder/v1/analysis.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalysisService_AnalyzeBatch_FullMethodName  = "/agenttransponder.v1.AnalysisService/AnalyzeBatch"
	AnalysisService_AnalyzeStream_FullMethodName = "/agenttransponder.v1.AnalysisService/AnalyzeStream"
	AnalysisService_ListDetectors_FullMethodName = "/agenttransponder.v1.AnalysisService/ListDetectors"
)

// AnalysisServiceClient is the client API for AnalysisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AnalysisService runs on the Python analysis engine.
// The Go ingestion service calls this to submit events for classification.
type AnalysisServiceClient interface {
	// Analyze a batch of events from a single session.
	AnalyzeBatch(ctx context.Context, in *AnalyzeBatchRequest, opts ...grpc.CallOption) (*AnalyzeBatchResponse, error)
	// Stream events for real-time analysis (stretch goal).
	AnalyzeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Event, Detection], error)
	// Check which detectors are loaded and healthy.
	ListDetectors(ctx context.Context, in *ListDetectorsRequest, opts ...grpc.CallOption) (*ListDetectorsResponse, error)
}

type analysisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalysisServiceClient(cc grpc.ClientConnInterface) AnalysisServiceClient {
	return &analysisServiceClient{cc}
}

func (c *analysisServiceClient) AnalyzeBatch(ctx context.Context, in *AnalyzeBatchRequest, opts ...grpc.CallOption) (*AnalyzeBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeBatchResponse)
	err := c.cc.Invoke(ctx, AnalysisService_AnalyzeBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisServiceClient) AnalyzeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Event, Detection], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AnalysisService_ServiceDesc.Streams[0], AnalysisService_AnalyzeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Event, Detection]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalysisService_AnalyzeStreamClient = grpc.BidiStreamingClient[Event, Detection]

func (c *analysisServiceClient) ListDetectors(ctx context.Context, in *ListDetectorsRequest, opts ...grpc.CallOption) (*ListDetectorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDetectorsResponse)
	err := c.cc.Invoke(ctx, AnalysisService_ListDetectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalysisServiceServer is the server API for AnalysisService service.
// All implementations must embed UnimplementedAnalysisServiceServer
// for forward compatibility.
//
// AnalysisService runs on the Python analysis engine.
// The Go ingestion service calls this to submit events for classification.
type AnalysisServiceServer interface {
	// Analyze a batch of events from a single session.
	AnalyzeBatch(context.Context, *AnalyzeBatchRequest) (*AnalyzeBatchResponse, error)
	// Stream events for real-time analysis (stretch goal).
	AnalyzeStream(grpc.BidiStreamingServer[Event, Detection]) error
	// Check which detectors are loaded and healthy.
	ListDetectors(context.Context, *ListDetectorsRequest) (*ListDetectorsResponse, error)
	mustEmbedUnimplementedAnalysisServiceServer()
}

// UnimplementedAnalysisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalysisServiceServer struct{}

func (UnimplementedAnalysisServiceServer) AnalyzeBatch(context.Context, *AnalyzeBatchRequest) (*AnalyzeBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeBatch not implemented")
}
func (UnimplementedAnalysisServiceServer) AnalyzeStream(grpc.BidiStreamingServer[Event, Detection]) error {
	return status.Error(codes.Unimplemented, "method AnalyzeStream not implemented")
}
func (UnimplementedAnalysisServiceServer) ListDetectors(context.Context, *ListDetectorsRequest) (*ListDetectorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDetectors not implemented")
}
func (UnimplementedAnalysisServiceServer) mustEmbedUnimplementedAnalysisServiceServer() {}
func (UnimplementedAnalysisServiceServer) testEmbeddedByValue()                         {}

// UnsafeAnalysisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalysisServiceServer will
// result in compilation errors.
type UnsafeAnalysisServiceServer interface {
	mustEmbedUnimplementedAnalysisServiceServer()
}

func RegisterAnalysisServiceServer(s grpc.ServiceRegistrar, srv AnalysisServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalysisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalysisService_ServiceDesc, srv)
}

func _AnalysisService_AnalyzeBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).AnalyzeBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_AnalyzeBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).AnalyzeBatch(ctx, req.(*AnalyzeBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalysisService_AnalyzeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AnalysisServiceServer).AnalyzeStream(&grpc.GenericServerStream[Event, Detection]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalysisService_AnalyzeStreamServer = grpc.BidiStreamingServer[Event, Detection]

func _AnalysisService_ListDetectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDetectorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).ListDetectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_ListDetectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).ListDetectors(ctx, req.(*ListDetectorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalysisService_ServiceDesc is the grpc.ServiceDesc for AnalysisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalysisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agenttransponder.v1.AnalysisService",
	HandlerType: (*AnalysisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeBatch",
			Handler:    _AnalysisService_AnalyzeBatch_Handler,
		},
		{
			MethodName: "ListDetectors",
			Handler:    _AnalysisService_ListDetectors_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AnalyzeStream",
			Handler:       _AnalysisService_AnalyzeStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/agenttransponder/v1/analysis.proto",
}
