// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/agenttransponder/v1/analysis.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DetectionType int32

const (
	DetectionType_DETECTION_TYPE_UNSPECIFIED       DetectionType = 0
	DetectionType_DETECTION_TYPE_TASK_LOOP         DetectionType = 1
	DetectionType_DETECTION_TYPE_TOOL_MISUSE       DetectionType = 2
	DetectionType_DETECTION_TYPE_GOAL_DRIFT        DetectionType = 3
	DetectionType_DETECTION_TYPE_HALLUCINATION     DetectionType = 4
	DetectionType_DETECTION_TYPE_FAILURE_CASCADE   DetectionType = 5
	DetectionType_DETECTION_TYPE_REWARD_HACKING    DetectionType = 6
	DetectionType_DETECTION_TYPE_PERSONALITY_DRIFT DetectionType = 7
)

// Enum value maps for DetectionType.
var (
	DetectionType_name = map[int32]string{
		0: "DETECTION_TYPE_UNSPECIFIED",
		1: "DETECTION_TYPE_TASK_LOOP",
		2: "DETECTION_TYPE_TOOL_MISUSE",
		3: "DETECTION_TYPE_GOAL_DRIFT",
		4: "DETECTION_TYPE_HALLUCINATION",
		5: "DETECTION_TYPE_FAILURE_CASCADE",
		6: "DETECTION_TYPE_REWARD_HACKING",
		7: "DETECTION_TYPE_PERSONALITY_DRIFT",
	}
	DetectionType_value = map[string]int32{
		"DETECTION_TYPE_UNSPECIFIED":       0,
		"DETECTION_TYPE_TASK_LOOP":         1,
		"DETECTION_TYPE_TOOL_MISUSE":       2,
		"DETECTION_TYPE_GOAL_DRIFT":        3,
		"DETECTION_TYPE_HALLUCINATION":     4,
		"DETECTION_TYPE_FAILURE_CASCADE":   5,
		"DETECTION_TYPE_REWARD_HACKING":    6,
		"DETECTION_TYPE_PERSONALITY_DRIFT": 7,
	}
)

func (x DetectionType) Enum() *DetectionType {
	p := new(DetectionType)
	*p = x
	return p
}

func (x DetectionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DetectionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agenttransponder_v1_analysis_proto_enumTypes[0].Descriptor()
}

func (DetectionType) Type() protoreflect.EnumType {
	return &file_proto_agenttransponder_v1_analysis_proto_enumTypes[0]
}

func (x DetectionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DetectionType.Descriptor instead.
func (DetectionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_agenttransponder_v1_analysis_proto_rawDescGZIP(), []int{0}
}

type AnalyzeBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Events        []*Event               `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeBatchRequest) Reset() {
	*x = AnalyzeBatchRequest{}
	mi := &file_proto_agenttransponder_v1_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeBatchRequest) ProtoMessage() {}

func (x *AnalyzeBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agenttransponder_v1_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeBatchRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_agenttransponder_v1_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeBatchRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AnalyzeBatchRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AnalyzeBatchRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AnalyzeBatchRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type AnalyzeBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detections    []*Detection           `protobuf:"bytes,1,rep,name=detections,proto3" json:"detections,omitempty"`
	Metadata      *AnalysisMetadata      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeBatchResponse) Reset() {
	*x = AnalyzeBatchResponse{}
	mi := &file_proto_agenttransponder_v1_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeBatchResponse) ProtoMessage() {}

func (x *AnalyzeBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agenttransponder_v1_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeBatchResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_agenttransponder_v1_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeBatchResponse) GetDetections() []*Detection {
	if x != nil {
		return x.Detections
	}
	return nil
}

func (x *AnalyzeBatchResponse) GetMetadata() *AnalysisMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Detection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          DetectionType          `protobuf:"varint,1,opt,name=type,proto3,enum=agenttransponder.v1.DetectionType" json:"type,omitempty"`
	Severity      Severity               `protobuf:"varint,2,opt,name=severity,proto3,enum=agenttransponder.v1.Severity" json:"severity,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"` // 0.0–1.0
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	EventIds      []string               `protobuf:"bytes,5,rep,name=event_ids,json=eventIds,proto3" json:"event_ids,omitempty"` // Which events triggered this
	Evidence      string                 `protobuf:"bytes,6,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detection) Reset() {
	*x = Detection{}
	mi := &file_proto_agenttransponder_v1_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detection) ProtoMessage() {}

func (x *Detection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agenttransponder_v1_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detection.ProtoReflect.Descriptor instead.
func (*Detection) Descriptor() ([]byte, []int) {
	return file_proto_agenttransponder_v1_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *Detection) GetType() DetectionType {
	if x != nil {
		return x.Type
	}
	return DetectionType_DETECTION_TYPE_UNSPECIFIED
}

func (x *Detection) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Detection) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Detection) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Detection) GetEventIds() []string {
	if x != nil {
		return x.EventIds
	}
	return nil
}

func (x *Detection) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

type AnalysisMetadata struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AnalyzedAt          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=analyzed_at,json=analyzedAt,proto3" json:"analyzed_at,omitempty"`
	EventsProcessed     int32                  `protobuf:"varint,2,opt,name=events_processed,json=eventsProcessed,proto3" json:"events_processed,omitempty"`
	DetectionsFound     int32                  `protobuf:"varint,3,opt,name=detections_found,json=detectionsFound,proto3" json:"detections_found,omitempty"`
	DetectorLatenciesMs map[string]float64     `protobuf:"bytes,4,rep,name=detector_latencies_ms,json=detectorLatenciesMs,proto3" json:"detector_latencies_ms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // Per-detector timing
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AnalysisMetadata) Reset() {
	*x = AnalysisMetadata{}
	mi := &file_proto_agenttransponder_v1_analysis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisMetadata) ProtoMessage() {}

func (x *AnalysisMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agenttransponder_v1_analysis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisMetadata.ProtoReflect.Descriptor instead.
func (*AnalysisMetadata) Descriptor() ([]byte, []int) {
	return file_proto_agenttransponder_v1_analysis_proto_rawDescGZIP(), []int{3}
}

func (x *AnalysisMetadata) GetAnalyzedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AnalyzedAt
	}
	return nil
}

func (x *AnalysisMetadata) GetEventsProcessed() int32 {
	if x != nil {
		return x.EventsProcessed
	}
	return 0
}

func (x *AnalysisMetadata) GetDetectionsFound() int32 {
	if x != nil {
		return x.DetectionsFound
	}
	return 0
}

func (x *AnalysisMetadata) GetDetectorLatenciesMs() map[string]float64 {
	if x != nil {
		return x.DetectorLatenciesMs
	}
	return nil
}

type ListDetectorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDetectorsRequest) Reset() {
	*x = ListDetectorsRequest{}
	mi := &file_proto_agenttransponder_v1_analysis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDetectorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDetectorsRequest) ProtoMessage() {}

func (x *ListDetectorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agenttransponder_v1_analysis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDetectorsRequest.ProtoReflect.Descriptor instead.
func (*ListDetectorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_agenttransponder_v1_analysis_proto_rawDescGZIP(), []int{4}
}

type ListDetectorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detectors     []*DetectorInfo        `protobuf:"bytes,1,rep,name=detectors,proto3" json:"detectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDetectorsResponse) Reset() {
	*x = ListDetectorsResponse{}
	mi := &file_proto_agenttransponder_v1_analysis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDetectorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDetectorsResponse) ProtoMessage() {}

func (x *ListDetectorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agenttransponder_v1_analysis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDetectorsResponse.ProtoReflect.Descriptor instead.
func (*ListDetectorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_agenttransponder_v1_analysis_proto_rawDescGZIP(), []int{5}
}

func (x *ListDetectorsResponse) GetDetectors() []*DetectorInfo {
	if x != nil {
		return x.Detectors
	}
	return nil
}

type DetectorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Type          DetectionType          `protobuf:"varint,3,opt,name=type,proto3,enum=agenttransponder.v1.DetectionType" json:"type,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectorInfo) Reset() {
	*x = DetectorInfo{}
	mi := &file_proto_agenttransponder_v1_analysis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectorInfo) ProtoMessage() {}

func (x *DetectorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agenttransponder_v1_analysis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectorInfo.ProtoReflect.Descriptor instead.
func (*DetectorInfo) Descriptor() ([]byte, []int) {
	return file_proto_agenttransponder_v1_analysis_proto_rawDescGZIP(), []int{6}
}

func (x *DetectorInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DetectorInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DetectorInfo) GetType() DetectionType {
	if x != nil {
		return x.Type
	}
	return DetectionType_DETECTION_TYPE_UNSPECIFIED
}

func (x *DetectorInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *DetectorInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_proto_agenttransponder_v1_analysis_proto protoreflect.FileDescriptor

const file_proto_agenttransponder_v1_analysis_proto_rawDesc = "" +
	"\n" +
	"(proto/agenttransponder/v1/analysis.proto\x12\x13agenttransponder.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a&proto/agenttransponder/v1/events.proto\"\xa0\x01\n" +
	"\x13AnalyzeBatchRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x122\n" +
	"\x06events\x18\x04 \x03(\v2\x1a.agenttransponder.v1.EventR\x06events\"\x99\x01\n" +
	"\x14AnalyzeBatchResponse\x12>\n" +
	"\n" +
	"detections\x18\x01 \x03(\v2\x1e.agenttransponder.v1.DetectionR\n" +
	"detections\x12A\n" +
	"\bmetadata\x18\x02 \x01(\v2%.agenttransponder.v1.AnalysisMetadataR\bmetadata\"\xf1\x01\n" +
	"\tDetection\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".agenttransponder.v1.DetectionTypeR\x04type\x129\n" +
	"\bseverity\x18\x02 \x01(\x0e2\x1d.agenttransponder.v1.SeverityR\bseverity\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1b\n" +
	"\tevent_ids\x18\x05 \x03(\tR\beventIds\x12\x1a\n" +
	"\bevidence\x18\x06 \x01(\tR\bevidence\"\xe1\x02\n" +
	"\x10AnalysisMetadata\x12;\n" +
	"\vanalyzed_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"analyzedAt\x12)\n" +
	"\x10events_processed\x18\x02 \x01(\x05R\x0feventsProcessed\x12)\n" +
	"\x10detections_found\x18\x03 \x01(\x05R\x0fdetectionsFound\x12r\n" +
	"\x15detector_latencies_ms\x18\x04 \x03(\v2>.agenttransponder.v1.AnalysisMetadata.DetectorLatenciesMsEntryR\x13detectorLatenciesMs\x1aF\n" +
	"\x18DetectorLatenciesMsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x16\n" +
	"\x14ListDetectorsRequest\"X\n" +
	"\x15ListDetectorsResponse\x12?\n" +
	"\tdetectors\x18\x01 \x03(\v2!.agenttransponder.v1.DetectorInfoR\tdetectors\"\xb0\x01\n" +
	"\fDetectorInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x126\n" +
	"\x04type\x18\x03 \x01(\x0e2\".agenttransponder.v1.DetectionTypeR\x04type\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription*\x9b\x02\n" +
	"\rDetectionType\x12\x1e\n" +
	"\x1aDETECTION_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DETECTION_TYPE_TASK_LOOP\x10\x01\x12\x1e\n" +
	"\x1aDETECTION_TYPE_TOOL_MISUSE\x10\x02\x12\x1d\n" +
	"\x19DETECTION_TYPE_GOAL_DRIFT\x10\x03\x12 \n" +
	"\x1cDETECTION_TYPE_HALLUCINATION\x10\x04\x12\"\n" +
	"\x1eDETECTION_TYPE_FAILURE_CASCADE\x10\x05\x12!\n" +
	"\x1dDETECTION_TYPE_REWARD_HACKING\x10\x06\x12$\n" +
	" DETECTION_TYPE_PERSONALITY_DRIFT\x10\a2\xaf\x02\n" +
	"\x0fAnalysisService\x12c\n" +
	"\fAnalyzeBatch\x12(.agenttransponder.v1.AnalyzeBatchRequest\x1a).agenttransponder.v1.AnalyzeBatchResponse\x12O\n" +
	"\rAnalyzeStream\x12\x1a.agenttransponder.v1.Event\x1a\x1e.agenttransponder.v1.Detection(\x010\x01\x12f\n" +
	"\rListDetectors\x12).agenttransponder.v1.ListDetectorsRequest\x1a*.agenttransponder.v1.ListDetectorsResponseBJZHgithub.com/agent-transponder/agent-transponder/proto/agenttransponder/v1b\x06proto3"

var (
	file_proto_agenttransponder_v1_analysis_proto_rawDescOnce sync.Once
	file_proto_agenttransponder_v1_analysis_proto_rawDescData []byte
)

func file_proto_agenttransponder_v1_analysis_proto_rawDescGZIP() []byte {
	file_proto_agenttransponder_v1_analysis_proto_rawDescOnce.Do(func() {
		file_proto_agenttransponder_v1_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agenttransponder_v1_analysis_proto_rawDesc), len(file_proto_agenttransponder_v1_analysis_proto_rawDesc)))
	})
	return file_proto_agenttransponder_v1_analysis_proto_rawDescData
}

var file_proto_agenttransponder_v1_analysis_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_agenttransponder_v1_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_agenttransponder_v1_analysis_proto_goTypes = []any{
	(DetectionType)(0),            // 0: agenttransponder.v1.DetectionType
	(*AnalyzeBatchRequest)(nil),   // 1: agenttransponder.v1.AnalyzeBatchRequest
	(*AnalyzeBatchResponse)(nil),  // 2: agenttransponder.v1.AnalyzeBatchResponse
	(*Detection)(nil),             // 3: agenttransponder.v1.Detection
	(*AnalysisMetadata)(nil),      // 4: agenttransponder.v1.AnalysisMetadata
	(*ListDetectorsRequest)(nil),  // 5: agenttransponder.v1.ListDetectorsRequest
	(*ListDetectorsResponse)(nil), // 6: agenttransponder.v1.ListDetectorsResponse
	(*DetectorInfo)(nil),          // 7: agenttransponder.v1.DetectorInfo
	nil,                           // 8: agenttransponder.v1.AnalysisMetadata.DetectorLatenciesMsEntry
	(*Event)(nil),                 // 9: agenttransponder.v1.Event
	(Severity)(0),                 // 10: agenttransponder.v1.Severity
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_proto_agenttransponder_v1_analysis_proto_depIdxs = []int32{
	9,  // 0: agenttransponder.v1.AnalyzeBatchRequest.events:type_name -> agenttransponder.v1.Event
	3,  // 1: agenttransponder.v1.AnalyzeBatchResponse.detections:type_name -> agenttransponder.v1.Detection
	4,  // 2: agenttransponder.v1.AnalyzeBatchResponse.metadata:type_name -> agenttransponder.v1.AnalysisMetadata
	0,  // 3: agenttransponder.v1.Detection.type:type_name -> agenttransponder.v1.DetectionType
	10, // 4: agenttransponder.v1.Detection.severity:type_name -> agenttransponder.v1.Severity
	11, // 5: agenttransponder.v1.AnalysisMetadata.analyzed_at:type_name -> google.protobuf.Timestamp
	8,  // 6: agenttransponder.v1.AnalysisMetadata.detector_latencies_ms:type_name -> agenttransponder.v1.AnalysisMetadata.DetectorLatenciesMsEntry
	7,  // 7: agenttransponder.v1.ListDetectorsResponse.detectors:type_name -> agenttransponder.v1.DetectorInfo
	0,  // 8: agenttransponder.v1.DetectorInfo.type:type_name -> agenttransponder.v1.DetectionType
	1,  // 9: agenttransponder.v1.AnalysisService.AnalyzeBatch:input_type -> agenttransponder.v1.AnalyzeBatchRequest
	9,  // 10: agenttransponder.v1.AnalysisService.AnalyzeStream:input_type -> agenttransponder.v1.Event
	5,  // 11: agenttransponder.v1.AnalysisService.ListDetectors:input_type -> agenttransponder.v1.ListDetectorsRequest
	2,  // 12: agenttransponder.v1.AnalysisService.AnalyzeBatch:output_type -> agenttransponder.v1.AnalyzeBatchResponse
	3,  // 13: agenttransponder.v1.AnalysisService.AnalyzeStream:output_type -> agenttransponder.v1.Detection
	6,  // 14: agenttransponder.v1.AnalysisService.ListDetectors:output_type -> agenttransponder.v1.ListDetectorsResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_agenttransponder_v1_analysis_proto_init() }
func file_proto_agenttransponder_v1_analysis_proto_init() {
	if File_proto_agenttransponder_v1_analysis_proto != nil {
		return
	}
	file_proto_agenttransponder_v1_events_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agenttransponder_v1_analysis_proto_rawDesc), len(file_proto_agenttransponder_v1_analysis_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agenttransponder_v1_analysis_proto_goTypes,
		DependencyIndexes: file_proto_agenttransponder_v1_analysis_proto_depIdxs,
		EnumInfos:         file_proto_agenttransponder_v1_analysis_proto_enumTypes,
		MessageInfos:      file_proto_agenttransponder_v1_analysis_proto_msgTypes,
	}.Build()
	File_proto_agenttransponder_v1_analysis_proto = out.File
	file_proto_agenttransponder_v1_analysis_proto_goTypes = nil
	file_proto_agenttransponder_v1_analysis_proto_depIdxs = nil
}
