// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/agenttransponder/v1/events.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED    EventType = 0
	EventType_EVENT_TYPE_PROMPT         EventType = 1
	EventType_EVENT_TYPE_RESPONSE       EventType = 2
	EventType_EVENT_TYPE_TOOL_CALL      EventType = 3
	EventType_EVENT_TYPE_TOOL_RESULT    EventType = 4
	EventType_EVENT_TYPE_MEMORY_READ    EventType = 5
	EventType_EVENT_TYPE_MEMORY_WRITE   EventType = 6
	EventType_EVENT_TYPE_REASONING_STEP EventType = 7
	EventType_EVENT_TYPE_ERROR          EventType = 8
	EventType_EVENT_TYPE_RETRY          EventType = 9
	EventType_EVENT_TYPE_METADATA       EventType = 10
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_TYPE_UNSPECIFIED",
		1:  "EVENT_TYPE_PROMPT",
		2:  "EVENT_TYPE_RESPONSE",
		3:  "EVENT_TYPE_TOOL_CALL",
		4:  "EVENT_TYPE_TOOL_RESULT",
		5:  "EVENT_TYPE_MEMORY_READ",
		6:  "EVENT_TYPE_MEMORY_WRITE",
		7:  "EVENT_TYPE_REASONING_STEP",
		8:  "EVENT_TYPE_ERROR",
		9:  "EVENT_TYPE_RETRY",
		10: "EVENT_TYPE_METADATA",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":    0,
		"EVENT_TYPE_PROMPT":         1,
		"EVENT_TYPE_RESPONSE":       2,
		"EVENT_TYPE_TOOL_CALL":      3,
		"EVENT_TYPE_TOOL_RESULT":    4,
		"EVENT_TYPE_MEMORY_READ":    5,
		"EVENT_TYPE_MEMORY_WRITE":   6,
		"EVENT_TYPE_REASONING_STEP": 7,
		"EVENT_TYPE_ERROR":          8,
		"EVENT_TYPE_RETRY":          9,
		"EVENT_TYPE_METADATA":       10,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agenttransponder_v1_events_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_proto_agenttransponder_v1_events_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_agenttransponder_v1_events_proto_rawDescGZIP(), []int{0}
}

type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_DEBUG       Severity = 1
	Severity_SEVERITY_INFO        Severity = 2
	Severity_SEVERITY_WARNING     Severity = 3
	Severity_SEVERITY_ERROR       Severity = 4
	Severity_SEVERITY_CRITICAL    Severity = 5
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_DEBUG",
		2: "SEVERITY_INFO",
		3: "SEVERITY_WARNING",
		4: "SEVERITY_ERROR",
		5: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_DEBUG":       1,
		"SEVERITY_INFO":        2,
		"SEVERITY_WARNING":     3,
		"SEVERITY_ERROR":       4,
		"SEVERITY_CRITICAL":    5,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agenttransponder_v1_events_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_proto_agenttransponder_v1_events_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_proto_agenttransponder_v1_events_proto_rawDescGZIP(), []int{1}
}

type IngestEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventRequest) Reset() {
	*x = IngestEventRequest{}
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventRequest) ProtoMessage() {}

func (x *IngestEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventRequest.ProtoReflect.Descriptor instead.
func (*IngestEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_agenttransponder_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *IngestEventRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type IngestEventResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Accepted        bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	EventId         string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Error           string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                                            // Non-empty if rejected
	RejectionReason string                 `protobuf:"bytes,4,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"` // "invalid_hmac", "rate_limited", "schema_violation", etc.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IngestEventResponse) Reset() {
	*x = IngestEventResponse{}
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventResponse) ProtoMessage() {}

func (x *IngestEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventResponse.ProtoReflect.Descriptor instead.
func (*IngestEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_agenttransponder_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *IngestEventResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *IngestEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *IngestEventResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *IngestEventResponse) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

type IngestEventStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AcceptedCount int64                  `protobuf:"varint,1,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	RejectedCount int64                  `protobuf:"varint,2,opt,name=rejected_count,json=rejectedCount,proto3" json:"rejected_count,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventStreamResponse) Reset() {
	*x = IngestEventStreamResponse{}
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventStreamResponse) ProtoMessage() {}

func (x *IngestEventStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventStreamResponse.ProtoReflect.Descriptor instead.
func (*IngestEventStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_agenttransponder_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *IngestEventStreamResponse) GetAcceptedCount() int64 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *IngestEventStreamResponse) GetRejectedCount() int64 {
	if x != nil {
		return x.RejectedCount
	}
	return 0
}

func (x *IngestEventStreamResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_agenttransponder_v1_events_proto_rawDescGZIP(), []int{3}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	AgentIdentity string                 `protobuf:"bytes,3,opt,name=agent_identity,json=agentIdentity,proto3" json:"agent_identity,omitempty"` // Echoes back the identity from the client cert
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_agenttransponder_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

func (x *PingResponse) GetAgentIdentity() string {
	if x != nil {
		return x.AgentIdentity
	}
	return ""
}

// Event mirrors the canonical event schema.
// Field numbers are stable — append only.
type Event struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentId   string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TenantId  string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Type      EventType              `protobuf:"varint,5,opt,name=type,proto3,enum=agenttransponder.v1.EventType" json:"type,omitempty"`
	Severity  Severity               `protobuf:"varint,6,opt,name=severity,proto3,enum=agenttransponder.v1.Severity" json:"severity,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Duration  *durationpb.Duration   `protobuf:"bytes,8,opt,name=duration,proto3" json:"duration,omitempty"`
	// Content — at most one populated per event type
	Prompt     *PromptData       `protobuf:"bytes,10,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Response   *ResponseData     `protobuf:"bytes,11,opt,name=response,proto3" json:"response,omitempty"`
	ToolCall   *ToolCallData     `protobuf:"bytes,12,opt,name=tool_call,json=toolCall,proto3" json:"tool_call,omitempty"`
	Memory     *MemoryData       `protobuf:"bytes,13,opt,name=memory,proto3" json:"memory,omitempty"`
	Reasoning  *ReasoningData    `protobuf:"bytes,14,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	Error      *ErrorData        `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`
	Model      string            `protobuf:"bytes,20,opt,name=model,proto3" json:"model,omitempty"`
	TokenUsage *TokenUsage       `protobuf:"bytes,21,opt,name=token_usage,json=tokenUsage,proto3" json:"token_usage,omitempty"`
	Labels     map[string]string `protobuf:"bytes,22,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Causal attribution — populated by framework integrations.
	// run_id identifies this specific execution unit (LLM call, tool call, chain).
	// parent_run_id links to the enclosing execution unit, forming a tree.
	// Together they enable run-tree reconstruction for replay and
	// failure-cascade analysis.
	RunId       string `protobuf:"bytes,25,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ParentRunId string `protobuf:"bytes,26,opt,name=parent_run_id,json=parentRunId,proto3" json:"parent_run_id,omitempty"`
	// Framework-supplied tags for filtering and routing.
	// Preserved from the source framework (e.g. LangChain tags).
	Tags []string `protobuf:"bytes,27,rep,name=tags,proto3" json:"tags,omitempty"`
	// Integrity
	Hmac          string `protobuf:"bytes,30,opt,name=hmac,proto3" json:"hmac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_agenttransponder_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Event) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Event) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Event) GetPrompt() *PromptData {
	if x != nil {
		return x.Prompt
	}
	return nil
}

func (x *Event) GetResponse() *ResponseData {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *Event) GetToolCall() *ToolCallData {
	if x != nil {
		return x.ToolCall
	}
	return nil
}

func (x *Event) GetMemory() *MemoryData {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *Event) GetReasoning() *ReasoningData {
	if x != nil {
		return x.Reasoning
	}
	return nil
}

func (x *Event) GetError() *ErrorData {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Event) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Event) GetTokenUsage() *TokenUsage {
	if x != nil {
		return x.TokenUsage
	}
	return nil
}

func (x *Event) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Event) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Event) GetParentRunId() string {
	if x != nil {
		return x.ParentRunId
	}
	return ""
}

func (x *Event) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Event) GetHmac() string {
	if x != nil {
		return x.Hmac
	}
	return ""
}

type PromptData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	TokenCount    int32                  `protobuf:"varint,3,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptData) Reset() {
	*x = PromptData{}
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptData) ProtoMessage() {}

func (x *PromptData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptData.ProtoReflect.Descriptor instead.
func (*PromptData) Descriptor() ([]byte, []int) {
	return file_proto_agenttransponder_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *PromptData) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PromptData) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PromptData) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

type ResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	FinishReason  string                 `protobuf:"bytes,2,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	TokenCount    int32                  `protobuf:"varint,3,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseData) Reset() {
	*x = ResponseData{}
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseData) ProtoMessage() {}

func (x *ResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseData.ProtoReflect.Descriptor instead.
func (*ResponseData) Descriptor() ([]byte, []int) {
	return file_proto_agenttransponder_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *ResponseData) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ResponseData) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *ResponseData) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

type ToolCallData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolName      string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Arguments     *structpb.Struct       `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Result        *structpb.Struct       `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,5,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	RetryCount    int32                  `protobuf:"varint,6,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallData) Reset() {
	*x = ToolCallData{}
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallData) ProtoMessage() {}

func (x *ToolCallData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallData.ProtoReflect.Descriptor instead.
func (*ToolCallData) Descriptor() ([]byte, []int) {
	return file_proto_agenttransponder_v1_events_proto_rawDescGZIP(), []int{8}
}

func (x *ToolCallData) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCallData) GetArguments() *structpb.Struct {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *ToolCallData) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ToolCallData) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToolCallData) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ToolCallData) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

type MemoryData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryData) Reset() {
	*x = MemoryData{}
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryData) ProtoMessage() {}

func (x *MemoryData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryData.ProtoReflect.Descriptor instead.
func (*MemoryData) Descriptor() ([]byte, []int) {
	return file_proto_agenttransponder_v1_events_proto_rawDescGZIP(), []int{9}
}

func (x *MemoryData) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *MemoryData) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MemoryData) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ReasoningData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          int32                  `protobuf:"varint,1,opt,name=step,proto3" json:"step,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReasoningData) Reset() {
	*x = ReasoningData{}
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasoningData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasoningData) ProtoMessage() {}

func (x *ReasoningData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasoningData.ProtoReflect.Descriptor instead.
func (*ReasoningData) Descriptor() ([]byte, []int) {
	return file_proto_agenttransponder_v1_events_proto_rawDescGZIP(), []int{10}
}

func (x *ReasoningData) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *ReasoningData) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ErrorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Stacktrace    string                 `protobuf:"bytes,3,opt,name=stacktrace,proto3" json:"stacktrace,omitempty"`
	Retryable     bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorData) Reset() {
	*x = ErrorData{}
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorData) ProtoMessage() {}

func (x *ErrorData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorData.ProtoReflect.Descriptor instead.
func (*ErrorData) Descriptor() ([]byte, []int) {
	return file_proto_agenttransponder_v1_events_proto_rawDescGZIP(), []int{11}
}

func (x *ErrorData) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorData) GetStacktrace() string {
	if x != nil {
		return x.Stacktrace
	}
	return ""
}

func (x *ErrorData) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type TokenUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agenttransponder_v1_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_proto_agenttransponder_v1_events_proto_rawDescGZIP(), []int{12}
}

func (x *TokenUsage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *TokenUsage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *TokenUsage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

var File_proto_agenttransponder_v1_events_proto protoreflect.FileDescriptor

const file_proto_agenttransponder_v1_events_proto_rawDesc = "" +
	"\n" +
	"&proto/agenttransponder/v1/events.proto\x12\x13agenttransponder.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\"F\n" +
	"\x12IngestEventRequest\x120\n" +
	"\x05event\x18\x01 \x01(\v2\x1a.agenttransponder.v1.EventR\x05event\"\x8d\x01\n" +
	"\x13IngestEventResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12)\n" +
	"\x10rejection_reason\x18\x04 \x01(\tR\x0frejectionReason\"\x81\x01\n" +
	"\x19IngestEventStreamResponse\x12%\n" +
	"\x0eaccepted_count\x18\x01 \x01(\x03R\racceptedCount\x12%\n" +
	"\x0erejected_count\x18\x02 \x01(\x03R\rrejectedCount\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\"\r\n" +
	"\vPingRequest\"\x8c\x01\n" +
	"\fPingResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12;\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\x12%\n" +
	"\x0eagent_identity\x18\x03 \x01(\tR\ragentIdentity\"\xed\a\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x122\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1e.agenttransponder.v1.EventTypeR\x04type\x129\n" +
	"\bseverity\x18\x06 \x01(\x0e2\x1d.agenttransponder.v1.SeverityR\bseverity\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x125\n" +
	"\bduration\x18\b \x01(\v2\x19.google.protobuf.DurationR\bduration\x127\n" +
	"\x06prompt\x18\n" +
	" \x01(\v2\x1f.agenttransponder.v1.PromptDataR\x06prompt\x12=\n" +
	"\bresponse\x18\v \x01(\v2!.agenttransponder.v1.ResponseDataR\bresponse\x12>\n" +
	"\ttool_call\x18\f \x01(\v2!.agenttransponder.v1.ToolCallDataR\btoolCall\x127\n" +
	"\x06memory\x18\r \x01(\v2\x1f.agenttransponder.v1.MemoryDataR\x06memory\x12@\n" +
	"\treasoning\x18\x0e \x01(\v2\".agenttransponder.v1.ReasoningDataR\treasoning\x124\n" +
	"\x05error\x18\x0f \x01(\v2\x1e.agenttransponder.v1.ErrorDataR\x05error\x12\x14\n" +
	"\x05model\x18\x14 \x01(\tR\x05model\x12@\n" +
	"\vtoken_usage\x18\x15 \x01(\v2\x1f.agenttransponder.v1.TokenUsageR\n" +
	"tokenUsage\x12>\n" +
	"\x06labels\x18\x16 \x03(\v2&.agenttransponder.v1.Event.LabelsEntryR\x06labels\x12\x15\n" +
	"\x06run_id\x18\x19 \x01(\tR\x05runId\x12\"\n" +
	"\rparent_run_id\x18\x1a \x01(\tR\vparentRunId\x12\x12\n" +
	"\x04tags\x18\x1b \x03(\tR\x04tags\x12\x12\n" +
	"\x04hmac\x18\x1e \x01(\tR\x04hmac\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"[\n" +
	"\n" +
	"PromptData\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1f\n" +
	"\vtoken_count\x18\x03 \x01(\x05R\n" +
	"tokenCount\"n\n" +
	"\fResponseData\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12#\n" +
	"\rfinish_reason\x18\x02 \x01(\tR\ffinishReason\x12\x1f\n" +
	"\vtoken_count\x18\x03 \x01(\x05R\n" +
	"tokenCount\"\xeb\x01\n" +
	"\fToolCallData\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x125\n" +
	"\targuments\x18\x02 \x01(\v2\x17.google.protobuf.StructR\targuments\x12/\n" +
	"\x06result\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06result\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x05 \x01(\tR\berrorMsg\x12\x1f\n" +
	"\vretry_count\x18\x06 \x01(\x05R\n" +
	"retryCount\"R\n" +
	"\n" +
	"MemoryData\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"=\n" +
	"\rReasoningData\x12\x12\n" +
	"\x04step\x18\x01 \x01(\x05R\x04step\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"w\n" +
	"\tErrorData\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"stacktrace\x18\x03 \x01(\tR\n" +
	"stacktrace\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\"\x81\x01\n" +
	"\n" +
	"TokenUsage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens*\xaa\x02\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EVENT_TYPE_PROMPT\x10\x01\x12\x17\n" +
	"\x13EVENT_TYPE_RESPONSE\x10\x02\x12\x18\n" +
	"\x14EVENT_TYPE_TOOL_CALL\x10\x03\x12\x1a\n" +
	"\x16EVENT_TYPE_TOOL_RESULT\x10\x04\x12\x1a\n" +
	"\x16EVENT_TYPE_MEMORY_READ\x10\x05\x12\x1b\n" +
	"\x17EVENT_TYPE_MEMORY_WRITE\x10\x06\x12\x1d\n" +
	"\x19EVENT_TYPE_REASONING_STEP\x10\a\x12\x14\n" +
	"\x10EVENT_TYPE_ERROR\x10\b\x12\x14\n" +
	"\x10EVENT_TYPE_RETRY\x10\t\x12\x17\n" +
	"\x13EVENT_TYPE_METADATA\x10\n" +
	"*\x8c\x01\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSEVERITY_DEBUG\x10\x01\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x02\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x03\x12\x12\n" +
	"\x0eSEVERITY_ERROR\x10\x04\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x052\xaf\x02\n" +
	"\x0eEventIngestion\x12`\n" +
	"\vIngestEvent\x12'.agenttransponder.v1.IngestEventRequest\x1a(.agenttransponder.v1.IngestEventResponse\x12n\n" +
	"\x11IngestEventStream\x12'.agenttransponder.v1.IngestEventRequest\x1a..agenttransponder.v1.IngestEventStreamResponse(\x01\x12K\n" +
	"\x04Ping\x12 .agenttransponder.v1.PingRequest\x1a!.agenttransponder.v1.PingResponseBJZHgithub.com/agent-transponder/agent-transponder/proto/agenttransponder/v1b\x06proto3"

var (
	file_proto_agenttransponder_v1_events_proto_rawDescOnce sync.Once
	file_proto_agenttransponder_v1_events_proto_rawDescData []byte
)

func file_proto_agenttransponder_v1_events_proto_rawDescGZIP() []byte {
	file_proto_agenttransponder_v1_events_proto_rawDescOnce.Do(func() {
		file_proto_agenttransponder_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agenttransponder_v1_events_proto_rawDesc), len(file_proto_agenttransponder_v1_events_proto_rawDesc)))
	})
	return file_proto_agenttransponder_v1_events_proto_rawDescData
}

var file_proto_agenttransponder_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_agenttransponder_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_agenttransponder_v1_events_proto_goTypes = []any{
	(EventType)(0),                    // 0: agenttransponder.v1.EventType
	(Severity)(0),                     // 1: agenttransponder.v1.Severity
	(*IngestEventRequest)(nil),        // 2: agenttransponder.v1.IngestEventRequest
	(*IngestEventResponse)(nil),       // 3: agenttransponder.v1.IngestEventResponse
	(*IngestEventStreamResponse)(nil), // 4: agenttransponder.v1.IngestEventStreamResponse
	(*PingRequest)(nil),               // 5: agenttransponder.v1.PingRequest
	(*PingResponse)(nil),              // 6: agenttransponder.v1.PingResponse
	(*Event)(nil),                     // 7: agenttransponder.v1.Event
	(*PromptData)(nil),                // 8: agenttransponder.v1.PromptData
	(*ResponseData)(nil),              // 9: agenttransponder.v1.ResponseData
	(*ToolCallData)(nil),              // 10: agenttransponder.v1.ToolCallData
	(*MemoryData)(nil),                // 11: agenttransponder.v1.MemoryData
	(*ReasoningData)(nil),             // 12: agenttransponder.v1.ReasoningData
	(*ErrorData)(nil),                 // 13: agenttransponder.v1.ErrorData
	(*TokenUsage)(nil),                // 14: agenttransponder.v1.TokenUsage
	nil,                               // 15: agenttransponder.v1.Event.LabelsEntry
	(*timestamppb.Timestamp)(nil),     // 16: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),       // 17: google.protobuf.Duration
	(*structpb.Struct)(nil),           // 18: google.protobuf.Struct
}
var file_proto_agenttransponder_v1_events_proto_depIdxs = []int32{
	7,  // 0: agenttransponder.v1.IngestEventRequest.event:type_name -> agenttransponder.v1.Event
	16, // 1: agenttransponder.v1.PingResponse.server_time:type_name -> google.protobuf.Timestamp
	0,  // 2: agenttransponder.v1.Event.type:type_name -> agenttransponder.v1.EventType
	1,  // 3: agenttransponder.v1.Event.severity:type_name -> agenttransponder.v1.Severity
	16, // 4: agenttransponder.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	17, // 5: agenttransponder.v1.Event.duration:type_name -> google.protobuf.Duration
	8,  // 6: agenttransponder.v1.Event.prompt:type_name -> agenttransponder.v1.PromptData
	9,  // 7: agenttransponder.v1.Event.response:type_name -> agenttransponder.v1.ResponseData
	10, // 8: agenttransponder.v1.Event.tool_call:type_name -> agenttransponder.v1.ToolCallData
	11, // 9: agenttransponder.v1.Event.memory:type_name -> agenttransponder.v1.MemoryData
	12, // 10: agenttransponder.v1.Event.reasoning:type_name -> agenttransponder.v1.ReasoningData
	13, // 11: agenttransponder.v1.Event.error:type_name -> agenttransponder.v1.ErrorData
	14, // 12: agenttransponder.v1.Event.token_usage:type_name -> agenttransponder.v1.TokenUsage
	15, // 13: agenttransponder.v1.Event.labels:type_name -> agenttransponder.v1.Event.LabelsEntry
	18, // 14: agenttransponder.v1.ToolCallData.arguments:type_name -> google.protobuf.Struct
	18, // 15: agenttransponder.v1.ToolCallData.result:type_name -> google.protobuf.Struct
	2,  // 16: agenttransponder.v1.EventIngestion.IngestEvent:input_type -> agenttransponder.v1.IngestEventRequest
	2,  // 17: agenttransponder.v1.EventIngestion.IngestEventStream:input_type -> agenttransponder.v1.IngestEventRequest
	5,  // 18: agenttransponder.v1.EventIngestion.Ping:input_type -> agenttransponder.v1.PingRequest
	3,  // 19: agenttransponder.v1.EventIngestion.IngestEvent:output_type -> agenttransponder.v1.IngestEventResponse
	4,  // 20: agenttransponder.v1.EventIngestion.IngestEventStream:output_type -> agenttransponder.v1.IngestEventStreamResponse
	6,  // 21: agenttransponder.v1.EventIngestion.Ping:output_type -> agenttransponder.v1.PingResponse
	19, // [19:22] is the sub-list for method output_type
	16, // [16:19] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_agenttransponder_v1_events_proto_init() }
func file_proto_agenttransponder_v1_events_proto_init() {
	if File_proto_agenttransponder_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agenttransponder_v1_events_proto_rawDesc), len(file_proto_agenttransponder_v1_events_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agenttransponder_v1_events_proto_goTypes,
		DependencyIndexes: file_proto_agenttransponder_v1_events_proto_depIdxs,
		EnumInfos:         file_proto_agenttransponder_v1_events_proto_enumTypes,
		MessageInfos:      file_proto_agenttransponder_v1_events_proto_msgTypes,
	}.Build()
	File_proto_agenttransponder_v1_events_proto = out.File
	file_proto_agenttransponder_v1_events_proto_goTypes = nil
	file_proto_agenttransponder_v1_events_proto_depIdxs = nil
}
