// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/agenttransponder/v1/events.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventIngestion_IngestEvent_FullMethodName       = "/agenttransponder.v1.EventIngestion/IngestEvent"
	EventIngestion_IngestEventStream_FullMethodName = "/agenttransponder.v1.EventIngestion/IngestEventStream"
	EventIngestion_Ping_FullMethodName              = "/agenttransponder.v1.EventIngestion/Ping"
)

// EventIngestionClient is the client API for EventIngestion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EventIngestion is the service agents use to submit telemetry.
// The ingestion API implements this service.
type EventIngestionClient interface {
	// Submit a single event.
	IngestEvent(ctx context.Context, in *IngestEventRequest, opts ...grpc.CallOption) (*IngestEventResponse, error)
	// Submit a stream of events (for high-throughput agents).
	IngestEventStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IngestEventRequest, IngestEventStreamResponse], error)
	// Health check — used by SDK to verify connectivity and auth.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type eventIngestionClient struct {
	cc grpc.ClientConnInterface
}

func NewEventIngestionClient(cc grpc.ClientConnInterface) EventIngestionClient {
	return &eventIngestionClient{cc}
}

func (c *eventIngestionClient) IngestEvent(ctx context.Context, in *IngestEventRequest, opts ...grpc.CallOption) (*IngestEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestEventResponse)
	err := c.cc.Invoke(ctx, EventIngestion_IngestEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventIngestionClient) IngestEventStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IngestEventRequest, IngestEventStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventIngestion_ServiceDesc.Streams[0], EventIngestion_IngestEventStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IngestEventRequest, IngestEventStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventIngestion_IngestEventStreamClient = grpc.ClientStreamingClient[IngestEventRequest, IngestEventStreamResponse]

func (c *eventIngestionClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, EventIngestion_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventIngestionServer is the server API for EventIngestion service.
// All implementations must embed UnimplementedEventIngestionServer
// for forward compatibility.
//
// EventIngestion is the service agents use to submit telemetry.
// The ingestion API implements this service.
type EventIngestionServer interface {
	// Submit a single event.
	IngestEvent(context.Context, *IngestEventRequest) (*IngestEventResponse, error)
	// Submit a stream of events (for high-throughput agents).
	IngestEventStream(grpc.ClientStreamingServer[IngestEventRequest, IngestEventStreamResponse]) error
	// Health check — used by SDK to verify connectivity and auth.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedEventIngestionServer()
}

// UnimplementedEventIngestionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventIngestionServer struct{}

func (UnimplementedEventIngestionServer) IngestEvent(context.Context, *IngestEventRequest) (*IngestEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestEvent not implemented")
}
func (UnimplementedEventIngestionServer) IngestEventStream(grpc.ClientStreamingServer[IngestEventRequest, IngestEventStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method IngestEventStream not implemented")
}
func (UnimplementedEventIngestionServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedEventIngestionServer) mustEmbedUnimplementedEventIngestionServer() {}
func (UnimplementedEventIngestionServer) testEmbeddedByValue()                        {}

// UnsafeEventIngestionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventIngestionServer will
// result in compilation errors.
type UnsafeEventIngestionServer interface {
	mustEmbedUnimplementedEventIngestionServer()
}

func RegisterEventIngestionServer(s grpc.ServiceRegistrar, srv EventIngestionServer) {
	// If the following call panics, it indicates UnimplementedEventIngestionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventIngestion_ServiceDesc, srv)
}

func _EventIngestion_IngestEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventIngestionServer).IngestEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventIngestion_IngestEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventIngestionServer).IngestEvent(ctx, req.(*IngestEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventIngestion_IngestEventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventIngestionServer).IngestEventStream(&grpc.GenericServerStream[IngestEventRequest, IngestEventStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventIngestion_IngestEventStreamServer = grpc.ClientStreamingServer[IngestEventRequest, IngestEventStreamResponse]

func _EventIngestion_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventIngestionServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventIngestion_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventIngestionServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventIngestion_ServiceDesc is the grpc.ServiceDesc for EventIngestion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventIngestion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agenttransponder.v1.EventIngestion",
	HandlerType: (*EventIngestionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngestEvent",
			Handler:    _EventIngestion_IngestEvent_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _EventIngestion_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IngestEventStream",
			Handler:       _EventIngestion_IngestEventStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/agenttransponder/v1/events.proto",
}
