---
- name: OS-specific setup
  ansible.builtin.import_tasks: os_preflight.yml
  become: true

- name: Configure NTP time synchronization
  ansible.builtin.import_tasks: configure.yml

- name: Enable NTP service
  ansible.builtin.import_tasks: service.yml
