---
- name: OS-specific setup
  ansible.builtin.import_tasks: os_preflight.yml
  become: true

- name: Configure Grafana
  ansible.builtin.import_tasks: configure.yml

- name: Configure Grafana datasources
  ansible.builtin.import_tasks: datasources.yml

- name: Provision Grafana dashboards
  ansible.builtin.import_tasks: dashboards.yml

- name: Deploy Grafana systemd service
  ansible.builtin.import_tasks: service.yml
