---
- name: OS-specific setup
  ansible.builtin.import_tasks: os_preflight.yml
  become: true

- name: Configure Prometheus
  ansible.builtin.import_tasks: configure.yml

- name: Deploy Prometheus systemd service
  ansible.builtin.import_tasks: service.yml
