---
- name: Template Prometheus systemd service unit
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: "0644"
  notify: restart prometheus

- name: Enable and start Prometheus service
  ansible.builtin.systemd:
    name: prometheus
    enabled: true
    state: started
    daemon_reload: true
