---
- name: Install auditd
  ansible.builtin.package:
    name:  auditd
    state: present

- name: Deploy audit rules
  ansible.builtin.template:
    src:   audit.rules.j2
    dest:  /etc/audit/rules.d/hardening.rules
    owner: root
    group: root
    mode:  "0640"
  notify: Restart auditd

- name: Enable and start auditd
  ansible.builtin.service:
    name:    auditd
    enabled: true
    state:   started
