"""
Cross-language HMAC compatibility tests.

Verifies that Python's _canonical_json() produces output that matches what
Go's json.Marshal produces for the same event. Since we cannot run Go inside
a Python test, we hardcode the expected canonical JSON generated by:

    go run ./cmd/hmaccheck/

Both must be identical — any difference means the HMAC will never verify.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone

from agent_transponder.events import Event, EventType, Severity
from agent_transponder.hmac import _canonical_json


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Go zero time — time.Time{} marshalled by Go's time package
_GO_ZERO_TIME = "0001-01-01T00:00:00Z"


def _minimal_event() -> Event:
    """Return the canonical test event that cmd/hmaccheck/main.go also uses."""
    return Event(
        id="test-123",
        session_id="sess-1",
        agent_id="sdk-demo",
        tenant_id="demo",
        type=EventType.PROMPT,
        severity=Severity.INFO,
        timestamp=datetime(1, 1, 1, tzinfo=timezone.utc),
        received_at=datetime(1, 1, 1, tzinfo=timezone.utc),
    )


# ---------------------------------------------------------------------------
# Structural invariants
# ---------------------------------------------------------------------------


def test_type_serialised_as_string():
    e = _minimal_event()
    data = json.loads(_canonical_json(e))
    assert data["type"] == "prompt", f"expected 'prompt', got {data['type']!r}"


def test_severity_serialised_as_string():
    e = _minimal_event()
    data = json.loads(_canonical_json(e))
    assert data["severity"] == "info", f"expected 'info', got {data['severity']!r}"


def test_hmac_excluded_from_canonical_json():
    e = _minimal_event()
    e.hmac = "should-be-excluded"
    data = json.loads(_canonical_json(e))
    assert "hmac" not in data


def test_timestamp_uses_z_suffix():
    e = _minimal_event()
    data = json.loads(_canonical_json(e))
    assert data["timestamp"].endswith("Z"), (
        f"timestamp must end with 'Z', got {data['timestamp']!r}"
    )
    assert data["received_at"].endswith("Z"), (
        f"received_at must end with 'Z', got {data['received_at']!r}"
    )


def test_zero_timestamp_matches_go():
    e = _minimal_event()
    data = json.loads(_canonical_json(e))
    assert data["timestamp"] == _GO_ZERO_TIME
    assert data["received_at"] == _GO_ZERO_TIME


def test_received_at_always_present():
    """Go always includes received_at (time.Time with omitempty is never empty)."""
    e = _minimal_event()
    data = json.loads(_canonical_json(e))
    assert "received_at" in data


def test_received_at_defaults_to_go_zero_time():
    """When received_at is None, it serialises as Go's zero time."""
    e = Event(
        id="x",
        session_id="s",
        agent_id="a",
        tenant_id="t",
        type=EventType.PROMPT,
        severity=Severity.INFO,
        timestamp=datetime(1, 1, 1, tzinfo=timezone.utc),
        # received_at not set → defaults to None
    )
    data = json.loads(_canonical_json(e))
    assert data["received_at"] == _GO_ZERO_TIME


def test_empty_model_omitted():
    """Go omits model when empty string (omitempty)."""
    e = _minimal_event()
    data = json.loads(_canonical_json(e))
    assert "model" not in data


def test_empty_labels_omitted():
    """Go omits labels when empty map (omitempty)."""
    e = _minimal_event()
    data = json.loads(_canonical_json(e))
    assert "labels" not in data


def test_zero_duration_omitted():
    """Go omits duration when zero (omitempty on int64)."""
    e = _minimal_event()
    data = json.loads(_canonical_json(e))
    assert "duration" not in data
    assert "duration_ms" not in data  # Python internal name must not leak


def test_nonzero_duration_uses_nanoseconds():
    """duration_ms is converted to nanoseconds and serialised as 'duration'."""
    e = _minimal_event()
    e.duration_ms = 100.0  # 100 ms = 100,000,000 ns
    data = json.loads(_canonical_json(e))
    assert data["duration"] == 100_000_000
    assert "duration_ms" not in data


def test_model_included_when_set():
    e = _minimal_event()
    e.model = "gpt-4o"
    data = json.loads(_canonical_json(e))
    assert data["model"] == "gpt-4o"


def test_labels_included_when_non_empty():
    e = _minimal_event()
    e.labels = {"env": "prod"}
    data = json.loads(_canonical_json(e))
    assert data["labels"] == {"env": "prod"}


def test_keys_sorted():
    """Canonical JSON must have alphabetically sorted keys (sort_keys=True)."""
    e = _minimal_event()
    payload = _canonical_json(e).decode("utf-8")
    data = json.loads(payload)
    reserialized = json.dumps(data, sort_keys=True, separators=(",", ":"))
    assert payload == reserialized


# ---------------------------------------------------------------------------
# Go-compatibility: exact canonical JSON match
# ---------------------------------------------------------------------------


def test_canonical_json_matches_go():
    """Verify Python canonical JSON matches Go json.Marshal output exactly.

    The expected value was generated by:
        go run ./cmd/hmaccheck/

    with the same test event (id=test-123, sess-1, sdk-demo, demo,
    type=prompt, severity=info, both timestamps = Go zero time).

    If this test fails, the HMAC will never verify between Go and Python.
    """
    e = _minimal_event()
    canonical = _canonical_json(e).decode("utf-8")
    parsed = json.loads(canonical)

    # Required fields — Go struct fields without omitempty
    assert parsed["id"] == "test-123"
    assert parsed["session_id"] == "sess-1"
    assert parsed["agent_id"] == "sdk-demo"
    assert parsed["tenant_id"] == "demo"
    assert parsed["type"] == "prompt"
    assert parsed["severity"] == "info"
    assert parsed["timestamp"] == _GO_ZERO_TIME
    assert parsed["received_at"] == _GO_ZERO_TIME

    # Fields that must be absent (omitempty, all zero/empty/nil)
    assert "hmac" not in parsed
    assert "model" not in parsed
    assert "labels" not in parsed
    assert "duration" not in parsed
    assert "duration_ms" not in parsed
    assert "prompt" not in parsed
    assert "response" not in parsed
    assert "tool_call" not in parsed
    assert "memory" not in parsed
    assert "reasoning" not in parsed
    assert "error" not in parsed
    assert "token_usage" not in parsed
    assert "run_id" not in parsed
    assert "parent_run_id" not in parsed
    assert "tags" not in parsed
    assert "redacted_fields" not in parsed

    # Exact field count — no extra fields
    assert set(parsed.keys()) == {
        "id",
        "session_id",
        "agent_id",
        "tenant_id",
        "type",
        "severity",
        "timestamp",
        "received_at",
    }


# ---------------------------------------------------------------------------
# EventType and Severity string values (all variants)
# ---------------------------------------------------------------------------


def test_all_event_type_strings():
    mapping = {
        EventType.PROMPT: "prompt",
        EventType.RESPONSE: "response",
        EventType.TOOL_CALL: "tool_call",
        EventType.TOOL_RESULT: "tool_result",
        EventType.MEMORY_READ: "memory_read",
        EventType.MEMORY_WRITE: "memory_write",
        EventType.REASONING_STEP: "reasoning_step",
        EventType.ERROR: "error",
        EventType.RETRY: "retry",
        EventType.METADATA: "metadata",
    }
    for et, expected in mapping.items():
        e = _minimal_event()
        e.type = et
        data = json.loads(_canonical_json(e))
        assert data["type"] == expected, (
            f"{et!r}: expected {expected!r}, got {data['type']!r}"
        )


def test_all_severity_strings():
    mapping = {
        Severity.DEBUG: "debug",
        Severity.INFO: "info",
        Severity.WARNING: "warning",
        Severity.ERROR: "error",
        Severity.CRITICAL: "critical",
    }
    for sev, expected in mapping.items():
        e = _minimal_event()
        e.severity = sev
        data = json.loads(_canonical_json(e))
        assert data["severity"] == expected, (
            f"{sev!r}: expected {expected!r}, got {data['severity']!r}"
        )
