# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agenttransponder.v1 import events_pb2 as agenttransponder_dot_v1_dot_events__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agenttransponder/v1/events_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventIngestionStub(object):
    """EventIngestion is the service agents use to submit telemetry.
    The ingestion API implements this service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestEvent = channel.unary_unary(
                '/agenttransponder.v1.EventIngestion/IngestEvent',
                request_serializer=agenttransponder_dot_v1_dot_events__pb2.IngestEventRequest.SerializeToString,
                response_deserializer=agenttransponder_dot_v1_dot_events__pb2.IngestEventResponse.FromString,
                _registered_method=True)
        self.IngestEventStream = channel.stream_unary(
                '/agenttransponder.v1.EventIngestion/IngestEventStream',
                request_serializer=agenttransponder_dot_v1_dot_events__pb2.IngestEventRequest.SerializeToString,
                response_deserializer=agenttransponder_dot_v1_dot_events__pb2.IngestEventStreamResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/agenttransponder.v1.EventIngestion/Ping',
                request_serializer=agenttransponder_dot_v1_dot_events__pb2.PingRequest.SerializeToString,
                response_deserializer=agenttransponder_dot_v1_dot_events__pb2.PingResponse.FromString,
                _registered_method=True)


class EventIngestionServicer(object):
    """EventIngestion is the service agents use to submit telemetry.
    The ingestion API implements this service.
    """

    def IngestEvent(self, request, context):
        """Submit a single event.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestEventStream(self, request_iterator, context):
        """Submit a stream of events (for high-throughput agents).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Health check — used by SDK to verify connectivity and auth.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventIngestionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestEvent,
                    request_deserializer=agenttransponder_dot_v1_dot_events__pb2.IngestEventRequest.FromString,
                    response_serializer=agenttransponder_dot_v1_dot_events__pb2.IngestEventResponse.SerializeToString,
            ),
            'IngestEventStream': grpc.stream_unary_rpc_method_handler(
                    servicer.IngestEventStream,
                    request_deserializer=agenttransponder_dot_v1_dot_events__pb2.IngestEventRequest.FromString,
                    response_serializer=agenttransponder_dot_v1_dot_events__pb2.IngestEventStreamResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=agenttransponder_dot_v1_dot_events__pb2.PingRequest.FromString,
                    response_serializer=agenttransponder_dot_v1_dot_events__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agenttransponder.v1.EventIngestion', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agenttransponder.v1.EventIngestion', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventIngestion(object):
    """EventIngestion is the service agents use to submit telemetry.
    The ingestion API implements this service.
    """

    @staticmethod
    def IngestEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agenttransponder.v1.EventIngestion/IngestEvent',
            agenttransponder_dot_v1_dot_events__pb2.IngestEventRequest.SerializeToString,
            agenttransponder_dot_v1_dot_events__pb2.IngestEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestEventStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/agenttransponder.v1.EventIngestion/IngestEventStream',
            agenttransponder_dot_v1_dot_events__pb2.IngestEventRequest.SerializeToString,
            agenttransponder_dot_v1_dot_events__pb2.IngestEventStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agenttransponder.v1.EventIngestion/Ping',
            agenttransponder_dot_v1_dot_events__pb2.PingRequest.SerializeToString,
            agenttransponder_dot_v1_dot_events__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
